#!/bin/bash

# This script reformats filenames from the MGISEQ-2000 to 10x 
# Genomics Cell Ranger-compatible names.

# File inputs
WORKING_DIR=$(dirname $PWD)
INPUT_CSV=${WORKING_DIR}/metadata/samplesheet.csv
INDEX_CSV=${WORKING_DIR}/metadata/chromium-shared-sample-indexes-plate.csv

# Define output path
OUTPUT_DIR=/shares/powell/data/experimental_data/PROCESSING/BGISeq_scRNA

for N in 2 3 4 5; do
    # Read elements from INPUT_CSV
    LINE=$(sed -n ${N}p  "$INPUT_CSV")
    IFS="," read -r SAMPLE INDEX FASTQ_DIR <<< "$LINE"
    SAMPLE_NUMBER=$(( $N - 1 ))
    # Define paths to write files out to
    SAMPLE_OUTPUT_DIR=$OUTPUT_DIR/$SAMPLE
    # mkdir -p $SAMPLE_OUTPUT_DIR
    echo $SAMPLE $INDEX $FASTQ_DIR $SAMPLE_OUTPUT_DIR

    # Retrieve line that matches the sample index
    INDEX_LINE=$(grep '^'${INDEX} $INDEX_CSV)

    # Parse line into an array so we can access them by number
    IFS="," read -r -a INDEX_ARRAY <<< "$INDEX_LINE"

    # For every lane, build a new name
    for X in 1 2 3 4; do
        SEQ="${INDEX_ARRAY[${X}]}"
        SAMPLE_NAME=${SAMPLE}_${SEQ}_S${SAMPLE_NUMBER}

        # Grab files generated by this set particular index
        # Change this to suite your file pattern
        FILE_LIST_R1=$( ls ${FASTQ_DIR}/*_${X}_1.fq.gz) 
        FILE_LIST_R2=$( ls ${FASTQ_DIR}/*_${X}_2.fq.gz) 

        echo "${FILE_LIST_R1[@]}"
        echo $"${FILE_LIST_R2[@]}"
    done
done
